#######################################################################
# Flash Cards Backend - CONFIGURATION                                 
#######################################################################
# You can use an ENV variable by using $(ENV_VAR_NAME) as the value

# ---------------------------------------------------------------------
# Database Connection String
# ---------------------------------------------------------------------

db: mongodb://localhost:27017/smartflash
env: 'development'
server:
  port: 3002